### ISSUE TITLE
Django Debug Enabled Revealing System, Database, and Configuration File Information

### ISSUE THREAD

**Issue by termireum** [SigmaGmbH/Bug-Bounty-1.0#14]
### 1. **Bug/Vulnerability Description**

Django Debug Enabled Revealing System, Database, and Configuration File Information

### 2. **Hardware and Software Specifications**

N/A

### 3. **Steps to Reproduce**

Visit https://issuer.sdi.swisstronik.com/ using the IP address 143.244.58.65.
The leaked information includes:
Django Version
Python Version
IP addresses
Database details (username, URL, type, port)

### 4. **Impact Analysis**

The disclosed information poses a potential risk as it allows an attacker to obtain details such as Django and Python versions, database type, database username, current database name, Django project configuration details, internal file paths, exception-generated source code, and local variables with their values. This information could empower an attacker to gain more insights and potentially develop further targeted attacks on the target system.

### 5. **Code Fix Submission**

Set DEBUG=False in your Django settings.py file

### 6. **Choose the Right Label**

Information Disclosure

### 7. **Additional Context**
![swisstronik](https://github.com/SigmaGmbH/Bug-Bounty-1.0/assets/72587681/15b35c43-9bc2-4933-9dce-11d23afec53e)

**Comment by SantiagoDevRel** [comment]
Hi @termireum , thank you so much for submitting this issue, we genuinely appreciate your commitment to our community and your dedication to improving the overall Swisstronik experience.
Please note that, unfortunately, this issue falls outside the scope of our bug bounty program, as outlined [here](https://github.com/SigmaGmbH/Bug-Bounty-1.0/blob/main/OUT_OF_SCOPE.md)
Thank you💪
