### ISSUE TITLE
Access to RabbitMq Instance 

### ISSUE THREAD

**Issue by mabdullah22** [SigmaGmbH/Bug-Bounty-1.0#9]
### 1. **Bug/Vulnerability Description**

Access to RabbitMq Instance 

### 2. **Hardware and Software Specifications**

N/A

### 3. **Steps to Reproduce**

There is a rabbitmq instance deployed at http://stage.panel.swisstronik.com:15672/

guest:guest credentials are valid but they are accessible via localhost only.
But I found that sigma:sigma credentials are also valid and gives me access to admin panel. 

### 4. **Impact Analysis**

An attacker can gain access to the instance and mess with it. Moreover he can dump the queues and publish messages.
### 5. **Code Fix Submission**

Apply strong credentials on the instance.

### 6. **Choose the Right Label**

Security Issue

### 7. **Additional Context** 

<img width="1512" alt="Screenshot 2023-10-13 at 9 14 27 PM" src="https://github.com/SigmaGmbH/Bug-Bounty-1.0/assets/31371789/8cd3603c-c2e6-4416-a760-6a362cee599a">

---

Thank you for contributing to the improvement of our project!👨‍💻👩‍💻

---

## Swisstronik internal use only

- [ ] Not duplicate issue
- [ ] Appropriate labels applied

**Comment by iNadirAli** [comment]
@santiagotrujilloz Please check

**Comment by SantiagoDevRel** [comment]
Issue closed [Hall of Fame](https://github.com/SigmaGmbH/Bug-Bounty-1.0/blob/main/Hall%20Of%20Fame/bug_report_by_mabdullah22_server.md)
